paragraphs_to_delete = [
"Welcome!  Designing a robust online learning experience requires a lot of up-front planning.  This guide is contains two resources: a course readiness self-check and a module design template. The quick resources section includes links to the Center for Teaching and Learning (CTL) website, which has quick articles on topics that might help you plan to meet those standards.",
"Please use this guide to organize the content for each week by filling in the highlighted areas. The guide may look long, but much it is notes and other helpful information meant as references to use when creating materials. In addition, you are welcome to include additional assignments, discussion forums, quizzes, etc., if that makes sense for your course.",
"Please leave notes here if there are items that need to be hidden from students, but visible to course facilitators. This can be helpful for portal integration notes, instructions for facilitating group work activities",
"if applicable, notes on how you use a course blog, or suggesting extra credit opportunities, etc. You might also consider where students will struggle in this lesson and suggest supplemental resources (which might already be available in the supplemental resources section) that may help students gain deeper understanding.",
"Draft key points which might be used in a message and/or announcement by the instructor during the live term concerning this module:",
"Historically, these areas are the ones that appear most often in later courses or are where students have struggled the most:",
"The following resources can be used as additional materials and/or alternatives to the ones already present in the module in situations where your live-term section would benefit from their use (such as a section composed largely of students with a particular area of concentration in common):",
"Please include an introduction to the lesson topic(s) here.  The introduction should be one to two written paragraphs briefly discussing the importance/relevance of the topic.  This should be written as if speaking to the student. (Video or audio are acceptable alternatives, but please provide a transcript or closed captioning as well.)",
"As you draft your introduction, consider how the module’s topics connect to the previous week, overall course and program objectives, and potential application beyond the learners’ academic career, including their future professional and personal development. This enhances the relevancy and frames the content. ",
"Objectives should be stated clearly in measurable terms based on Bloom’s Taxonomy, which presents measurable objectives across various combinations of the cognitive process and knowledge dimensions. ",
"For a list of measurable verbs, we suggest Revised Bloom’s Taxonomy Action Verbs from Azusa Pacific University.",
"Refer to your Course Map for your objectives. For examples, refer to the Course Map Examples document. ",
"List and describe any textbook or other reading assignments, Internet links, library articles, videos, interactives, tutorials, etc. that you require students to read or interact with in this module. Ideally, course materials are presented within a narrative explanation with an introduction, relevance, and how students can use the materials to accomplish objectives. ",
"Provide helpful hints and/or additional narrative to help students focus on the most important resources or concepts in the lesson. For example, give students guidance for how to move through the required materials or ask questions for them to consider while they work through the resources. This information is typically discipline specific, such as offering learners some acronyms to memorize parts of the body in nursing. ",
"Online courses should include study tools or suggestions (e.g., self-assessments, study guides, helpful hints). Consider any areas where your students will struggle and identify important or complicated topics and create and/or curate supportive materials to aid student success. List and describe any optional self-checks, Internet links, articles, readings, etc. that could be helpful for the struggling student or for the ambitious student who wants to know more. ",
"The course includes intentional opportunities for peer interaction and collaboration. It is recommended that at least one discussion activity be included each week.  Regular interaction with peers in the course is required. Discussion forums should not be recall activities, but drive students towards application of skills or analysis, in addition to evidence-based justification.  Consider going beyond that to have a discussion where students tie the content to their own lives and engage in reflection or transfer of learning outside of the parameters of the course.",
"Notes: AU Online requires student-to-student interactions in every module of the course. Also, the deadlines of Thursday/Sunday are standardized across all AU Online courses and all AU Online forums use the Q&A setting which requires learners to make their initial post before they can see their classmates’ posts. ",
"Introduce the discussion topic by providing any needed background information and context. Connect it to the module’s objective(s), content, and generate a broader sense of relevance. ",
"Consider drafting a sample response for learners, particularly for the first discussion board. This will “show” rather than “tell” them what is expected and they are more likely to move towards that level of achievement. ",
"Insert additional expectations/examples for appropriate replies to peers. ",
"(Note: A rubric is required for the discussion forums and will be linked to each discussion activity. Please add your rubric to the Rubrics Shared folder, where you can review some example rubrics from other AU Online courses.) ",
"Please provide instructions if you have an assignment you would like submitted for this lesson. When writing the activity, consider how the assignment drives higher order thinking (analysis, evaluation, synthesis, reflection, etc.). One model for building effective assignment prompts is the , from TILT Higher Ed",
"Provide a statement which guides learners to how the activity will benefit their learning and is connected to the learning objective. ",
"(Note: Rubrics are required for each open-ended assignment and will be linked to the activity. Please add your rubric to the Rubrics Shared folder, where you can review some example rubrics from other AU Online courses.)",
"(Note: Remember your course needs to add up to 1000 points. So keep this in mind as you decide on the total amount of your assignments/assessments.) ",
"Upload your rubric for discussions in the Rubrics folder. ",
"Please provide instructions if you have an assignment you would like submitted for this lesson. Examples might include partner work, peer reviews, group projects, draft submissions of individual projects or papers, etc. This could also be a reminder for learners to begin working on a larger assignment that is due in a future module.",
"Note: Rubrics are required for each open-ended assignment and will be linked to the activity. Please add your rubric to the Rubrics Shared folder, where you can review some example rubrics from other AU Online courses.)",
"(Note: Remember your course needs to add up to 1000points. So keep this in mind as you decide on the total amount of your assignments/assessments.)",
"Upload your rubric for discussions in the Rubrics folder.",
"An automatically scoring quiz/test/exam can be included where appropriate. These can be low-stakes formative activities or high-stakes summative assessments. A quiz/test can assess objective questions whereas the discussion forum will assess subjective.  Quizzes can incorporate multiple choice, true/false, as well as short essay. A minimum of 10 questions is generally recommended.",
"Please note any settings that should be applied to the quiz below:",
"Provide a list of actions learners should have completed for this module. For instance, a checklist might say something like:",
"Before moving on, be sure that you have (all required except those noted):",
"Note: Headers and sections align with the format in your Moodle master template, shown below.",
"Module Design Guide",
"Module Checklist (optional)",
"Online Course Design Guide",
"-Read Chapter 1",
"-Viewed the TedTalk",
"-Read the scholarly article on XYZ",
"-Reviewed the supplemental resources (optional)",
"-Taken the Self-Assessment (optional)",
"-Participated in the discussion board",
"-Submitted your assignment 1",
"-Posted a learning reflection (optional)",
"Insert module checklist here.",
"Quick Resources",
"Content Structure",
"Finding and Writing Good Content",
"Accessibility",
"Assessment",
"Group Work",
"Community",
"Discussion Boards"
]